<?php
  
  /**
   * Implements hook_menu().
   */
  function recia_menu() {
    $items['admin/config/system/recia'] = array(
      'title' => 'Recia module',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('recia_form'),
      'access arguments' => array('administer users'),
      'type' => MENU_NORMAL_ITEM,
    );

    return $items;
  }

  /**
 * Admin form to configurable welcome message
 */
  function recia_form($form, &$form_state) {
    watchdog('recia','recia_form');
    $modulesToManage = ['webform_confirm_email'];
    $modulesList = module_list();
    $form['recia_modules'] = array(
      '#type' => 'fieldset',
      '#title' => t('Modules gestion'),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,  
    );
    foreach ($modulesToManage as $module) {
      $form['recia_modules']['recia_modules_'.$module] = array(
        '#type' => 'radios',
        '#title' => $module,
        '#options' => array(t('disable'),t('enable')),
        '#default_value' => in_array($module, $modulesList)?1:0,
      );
    }
    
    $form['#submit'][] = 'recia_form_submit';

    return system_settings_form($form);
  }

  function recia_form_submit($form, &$form_state) {
    watchdog('recia','recia_form_submit');
    $modulesToManage = ['webform_confirm_email'];
    $modulesList = module_list();
    
    $modulesToEnable = [];
    $modulesToDisable = [];
    foreach($modulesToManage as $module){
      $module_enabled = in_array($module,$modulesList)?1:0;
      $module_enable = variable_get('recia_modules_'.$module,3);
      if($module_enable == 0 && $module_enabled == 1)$modulesToDisable[]=$module;
      if($module_enable == 1 && $module_enabled == 0)$modulesToEnable[]=$module;
    }
    watchdog('recia','modulesToDisable : '.print_r($modulesToDisable,true));
    watchdog('recia','modulesToEnable : '.print_r($modulesToEnable,true));
    if(count($modulesToDisable))module_disable($modulesToDisable,false);
    if(count($modulesToEnable))module_enable($modulesToEnable,false);
  }

  /**
   * Cron
   */
  function recia_cron() {
    /*
    $modulesList = module_list();
    $modulesToDisable = variable_get('recia_modules_disable',[]);
    if(count($modulesToDisable)){
      foreach($modu)
    }
    */
  }
  

  /**
   * Permissions
   */
  function recia_permission() {
    return array(
      'recia manage forms_templates' => array(
        'title' => t('Allow user to manage yakforms templates'),
        'restricted acces'=>true,
      )
    );
  }

  function recia_form_alter(&$form, &$form_state, $form_id) {
    $formsId = ['webform_node_form','form1_node_form'];
    if(!in_array($form_id,$formsId))return;
    $form['revision_information']['#access'] = false;
    $form['menu']['#access'] = false;
    $form['comment_settings']['#access'] = false;
    $form['path']['#access'] = false;
    $form['author']['#access'] = false;
    $form['options']['#access'] = false;
    $form['#attached']['css'] = [
      '#edit-field-form1-template {display:none;}',
      'inline'
    ];
    if(!user_access('recia manage forms_templates')){
      $form['field_form1_template']['#access'] = false;
      $form['field_form1_template_desc']['#access'] = false;
    }

    //$form['field_form1_results_public']['#access'] = false;
    //$form['field_form1_results_access']['#access'] = false;
  }

  function recia_menu_alter(&$items) {
    $items['node/%webform_menu/webform/ws-export']['access callback']='webform_share_menu_access';
  }

  function recia_block_info() {

    // This example comes from node.module.
    $blocks['recia_home_button'] = array(
      'info' => t('Recia : Return Home button'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    );
    $blocks['recia_user_menu_anonymous'] = array(
      'info' => t('Recia : User Menu (anonymous)'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED
    );
    $blocks['recia_user_menu'] = array(
      'info' => t('Recia : User Menu (user)'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
      'pages' => "node/add\nnode/add/*",
    );
    $blocks['recia_user_menu_redac'] = array(
      'info' => t('Recia : User Menu (editor)'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
      'pages' => "node/add\nnode/add/*",
    );
    $blocks['recia_user_menu_all'] = array(
      'info' => t('Recia : User Menu'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
      'pages' => "node/add\nnode/add/*",
    );
    $blocks['recia_form_menu'] = array(
      'info' => t('Recia : Form Menu'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    );
    $blocks['recia_form_menu_home'] = array(
      'info' => t('Recia : Form Menu Home'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
      'visibility' => BLOCK_VISIBILITY_NOTLISTED,
    );
    return $blocks;
  }

  function recia_block_view($delta) {
    global $user;
    global $base_url;
    $block = array();
    $logOutUrl = $base_url.'/user/logout';
    if (module_exists('cas')) $logOutUrl = $base_url.'/caslogout';
    switch($delta){
      case 'recia_home_button':
        if (!user_is_logged_in()) {
          return;
        }
        $block['content']['#markup'] ='<footer id="homeback">';
        $block['content']['#markup'] .='  <a class="button" href="'.$base_url.'">'.strtoupper(t('return to home')).'</a>';
        $block['content']['#markup'] .='</footer>';
        break;
      case 'recia_user_menu_anonymous':
         if (user_is_logged_in()) {
            return;
          }
          $block['content']['#markup'] =  '<div class="navbar-nav">';
          $block['content']['#markup'] .= ' <a href="'.$base_url.'" class="button btn btn-primary btn-sm" role="button">'.t("Log in").'</a>';
          $block['content']['#markup'] .= '</div>';
          $block['content']['#markup'] .= '</div>';
          break;
      case 'recia_user_menu':
        if (!user_is_logged_in()) {
          return;
        }
        $block['content']['#markup'] ='<div class="navbar-nav">';
        $block['content']['#markup'] .='  <div class="dropdown">';
        $block['content']['#markup'] .='    <button class="dropdown-toggle">';
        $block['content']['#markup'] .='      '.$user->name;
        $block['content']['#markup'] .='      <span class="caret"></span>';
        $block['content']['#markup'] .='    </button>';
        $block['content']['#markup'] .='    <ul class="dropdown-menu">';
        $block['content']['#markup'] .='      <li>';
        $block['content']['#markup'] .='        <a href="'.$logOutUrl.'">'.t('Disconnect').'</a>';
        $block['content']['#markup'] .='      </li>';
        $block['content']['#markup'] .='    </ul>';
        $block['content']['#markup'] .=' </div>';
        $block['content']['#markup'] .='</div>';
        break;
      case 'recia_user_menu_redac':
        if (!user_is_logged_in()) {
          return;
        }
        $block['content']['#markup'] ='<div class="navbar-nav">';
        $block['content']['#markup'] .='  <div class="dropdown">';
        $block['content']['#markup'] .='    <button class="button">';
        $block['content']['#markup'] .='      '.t("Create a new form");
        $block['content']['#markup'] .='      <span class="caret"></span>';
        $block['content']['#markup'] .='    </button>';
        $block['content']['#markup'] .='    <ul class="dropdown-menu">';
        $block['content']['#markup'] .='      <li>';
        $block['content']['#markup'] .='        <a href="'.$base_url.'/node/add/form1">'.t("Create a new form").'</a>';
        $block['content']['#markup'] .='      </li>';
        $block['content']['#markup'] .='      <li>';
        $block['content']['#markup'] .='        <a href="'.$base_url.'/templates">'.t("Create a form from a template").'</a>';
        $block['content']['#markup'] .='      </li>';
        $block['content']['#markup'] .='    </ul>';
        $block['content']['#markup'] .='  </div>';
        $block['content']['#markup'] .='  <div class="dropdown">';
        $block['content']['#markup'] .='    <button class="dropdown-toggle">';
        $block['content']['#markup'] .='      '.$user->name;
        $block['content']['#markup'] .='      <span class="caret"></span>';
        $block['content']['#markup'] .='    </button>';
        $block['content']['#markup'] .='    <ul class="dropdown-menu">';
        $block['content']['#markup'] .='      <li>';
        $block['content']['#markup'] .='        <a href="'.$base_url.'?forms">'.t('My forms').'</a>';
        $block['content']['#markup'] .='      </li>';
        $block['content']['#markup'] .='      <li>';
        $block['content']['#markup'] .='        <a href="'.$logOutUrl.'">'.t('Disconnect').'</a>';
        $block['content']['#markup'] .='      </li>';
        $block['content']['#markup'] .='    </ul>';
        $block['content']['#markup'] .='  </div>';
        $block['content']['#markup'] .='</div>';
        break;
        case 'recia_user_menu_all':
          if (!user_is_logged_in()) {
              /*$block['content']['#markup'] =  '<div class="navbar-nav">';
              $block['content']['#markup'] .= l(t("Connexion"),"cas",array('attributes'=> array('class' =>array('button','btn','btn-primary','btn-sm')),'query' => drupal_get_destination()));//' <a href="'.$base_url.'/" class="button btn btn-primary btn-sm" role="button">'.t("Log in").'</a>';
              $block['content']['#markup'] .= '</div>';
              $block['content']['#markup'] .= '</div>';*/
          }else{
            $block['content']['#markup'] ='<div class="navbar-nav">';
            if (user_access('create webform content') || user_access('create form1 content')) {
              $block['content']['#markup'] .='  <div class="dropdown">';
              $block['content']['#markup'] .='    <button class="button">';
              $block['content']['#markup'] .='      '.t("Create a new form");
              $block['content']['#markup'] .='      <span class="caret"></span>';
              $block['content']['#markup'] .='    </button>';
              $block['content']['#markup'] .='    <ul class="dropdown-menu">';
              $block['content']['#markup'] .='      <li>';
              $block['content']['#markup'] .='        <a href="'.$base_url.'/node/add/form1">'.t("Create a new form").'</a>';
              $block['content']['#markup'] .='      </li>';
              if (user_access('recia manage forms_templates')) {
                  $block['content']['#markup'] .='      <li>';
                  $block['content']['#markup'] .='        <a href="'.$base_url.'/templates">'.t("Create a form from a template").'</a>';
                  $block['content']['#markup'] .='      </li>';
              }
              $block['content']['#markup'] .='    </ul>';
              $block['content']['#markup'] .='  </div>';
            }
            $block['content']['#markup'] .='  <div class="dropdown">';
            $block['content']['#markup'] .='    <button class="dropdown-toggle">';
            $block['content']['#markup'] .='      '.$user->name;
            $block['content']['#markup'] .='      <span class="caret"></span>';
            $block['content']['#markup'] .='    </button>';
            $block['content']['#markup'] .='    <ul class="dropdown-menu">';
            if (user_access('create webform content') || user_access('create form1 content')) {
              $block['content']['#markup'] .='      <li>';
              $block['content']['#markup'] .='        <a href="'.$base_url.'?forms">'.t('My forms').'</a>';
              $block['content']['#markup'] .='      </li>';
            }
            $block['content']['#markup'] .='      <li>';
            $block['content']['#markup'] .='        <a href="'.$logOutUrl.'">'.t('Disconnect').'</a>';
            $block['content']['#markup'] .='      </li>';
            $block['content']['#markup'] .='    </ul>';
            $block['content']['#markup'] .='  </div>';
            $block['content']['#markup'] .='</div>';
          }
          break;
        case 'recia_form_menu':
          if (!user_is_logged_in() || (!user_access('create webform content') && !user_access('create form1 content'))) {
            return;
          }
          $block['content']['#markup'] ='<div class="navbar-nav">';
          $block['content']['#markup'] .='  <div class="dropdown">';
          $block['content']['#markup'] .='    <button class="button">';
          $block['content']['#markup'] .='      '.t("Create a new form");
          $block['content']['#markup'] .='      <span class="caret"></span>';
          $block['content']['#markup'] .='    </button>';
          $block['content']['#markup'] .='    <ul class="dropdown-menu">';
          $block['content']['#markup'] .='      <li>';
          $block['content']['#markup'] .='        <a href="'.$base_url.'/node/add/form1">'.t("Create a new form").'</a>';
          $block['content']['#markup'] .='      </li>';
          if (user_access('recia manage forms_templates')) {
              $block['content']['#markup'] .='      <li>';
              $block['content']['#markup'] .='        <a href="'.$base_url.'/templates">'.t("Create a form from a template").'</a>';
              $block['content']['#markup'] .='      </li>';
          }
          $block['content']['#markup'] .='    </ul>';
          $block['content']['#markup'] .='  </div>';
          $block['content']['#markup'] .='</div>';
          break;
        case 'recia_form_menu_home':
          if (!user_is_logged_in() || (!user_access('create webform content') && !user_access('create form1 content'))) {
            return;
          }
          $block['content']['#markup'] ='    <ul class="menu">';
          $block['content']['#markup'] .='      <li>';
          $block['content']['#markup'] .='        <a href="'.$base_url.'/node/add/form1">'.t("Create a new form").'</a>';
          $block['content']['#markup'] .='      </li>';
          if (user_access('recia manage forms_templates')) {
              $block['content']['#markup'] .='      <li>';
              $block['content']['#markup'] .='        <a href="'.$base_url.'/templates">'.t("Create a form from a template").'</a>';
              $block['content']['#markup'] .='      </li>';
          }
          $block['content']['#markup'] .='    </ul>';
          break;
    }
    return $block;
  }

  /**
   * Implements hook_views_api
   *
   * @return void
   */
  function recia_views_api () {
    return array(
      'api' => 3,
    );
  }

  /**
  * Implementation of hook_views_default_views
  **/
  function recia_views_default_views() {
    $views = array();
    $viewsPath = drupal_get_path('module', 'recia'). '/views';
    $files = file_scan_directory($viewsPath, '/\.view\.inc/');
    foreach ($files as $filepath => $file) {
      module_load_include('inc', 'recia', 'views/'.$file->name);
      $loader = str_replace(['.view','-'],'_',$file->name).'view_loader';
      if (function_exists($loader)) {
        $view = $loader();
        $views[$view->name] = $view;
      }
    }
    return $views;
  }
?>
